In [8]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [9]:
# Input Code

ui = input()
res = []
colors = []
while ui != "q":
    splitted = ui.split()
    res.append([int(splitted[0]), int(splitted[1]), int(splitted[2])])
    colors.append(splitted[3])
    ui = input()

X = np.array(res)
y = np.array([1 if color == "red" else 2 if color == "green" else 0 for color in colors])

115 37 59 white 115 35 61 white 123 244 32 red 131313 13131 3131 green
115 35 61 white 123 244 32 red 131313 13131 3131 green
123 244 32 red 131313 13131 3131 green
131313 13131 3131 green
q


In [14]:
X_boot = np.vstack([X for i in range(100)])
y_boot = np.hstack([y for i in range(100)])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_boot, y_boot, test_size=0.2, random_state=42, shuffle=True)

In [17]:
lr = LogisticRegression(multi_class="ovr")
lr.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [18]:
(lr.predict(X_test) == y_test).mean()

1.0

In [19]:
lr.coef_

array([[-0.00444426, -0.11504211,  0.01541597],
       [-0.01120306,  0.1154037 , -0.01603973],
       [ 0.01075361, -0.0676671 , -0.16166322]])

In [20]:
lr.intercept_

array([ 1.62681843e+01, -1.44280299e+01, -6.03167432e-03])

In [ ]:
def predict(r, b, g):
    idx = -1;
    champion = -1;
    for i in range(3):
        p = 1/(1 + np.exp(-((lr.coef_[i] * [r, b, g]).sum() + lr.intercept_[i])))
        if (champion <= p):
            idx = i;
            champion = p;
    return idx;

In [ ]:
predict(9, 115, 112)

0

In [ ]:
predict(161, 273, 321)

0

In [ ]:
lr.predict([[56, 217, 256]])

array([0])

In [ ]:
predict(78, 295, 332)

0

In [ ]:
predict(270, 294, 324)

2

In [ ]:
predict(308, 298, 331)

2

In [ ]:
predict(296, 290, 324)

2

In [ ]:
predict(72, 281, 393)

1

In [ ]:
predict(61, 275, 373)

1